-- NexusHub V1 建表草案；目标 MySQL 8.4，UTF8MB4，UTC。
-- 仅在专用空库执行；不含DROP、不含默认管理员密码。
SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE sys_user (
  id BIGINT NOT NULL COMMENT '应用生成的正整数ID',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'UTC创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'UTC更新时间，应用显式维护',
  create_by BIGINT NULL COMMENT '创建者，系统任务可空',
  update_by BIGINT NULL COMMENT '最后更新者',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除0正常1删除',
  username VARCHAR(64) NOT NULL COMMENT '规范化用户名，删除后不复用',
  display_name VARCHAR(64) NOT NULL COMMENT '显示名',
  password_hash VARCHAR(255) NOT NULL COMMENT 'BCrypt散列，不对外返回',
  role VARCHAR(16) NOT NULL COMMENT 'GUEST、USER或ADMIN',
  status VARCHAR(16) NOT NULL DEFAULT 'ENABLED' COMMENT '账号状态',
  row_version INT NOT NULL DEFAULT 0 COMMENT '并发版本',
  credential_version INT NOT NULL DEFAULT 0 COMMENT '重置/停用时递增以撤销会话',
  PRIMARY KEY (id),
  CONSTRAINT ck_sys_user_deleted CHECK (deleted IN (0,1)),
  UNIQUE KEY uk_user_username (username),
  CHECK (role IN ('GUEST','USER','ADMIN')),
  CHECK (status IN ('ENABLED','DISABLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='本系统账号；固定单角色';

CREATE TABLE hub_system (
  id BIGINT NOT NULL COMMENT '应用生成的正整数ID',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'UTC创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'UTC更新时间，应用显式维护',
  create_by BIGINT NULL COMMENT '创建者，系统任务可空',
  update_by BIGINT NULL COMMENT '最后更新者',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除0正常1删除',
  code VARCHAR(64) NOT NULL COMMENT '不可变唯一编码',
  name VARCHAR(64) NOT NULL COMMENT '名称',
  description VARCHAR(300) NOT NULL DEFAULT '' COMMENT '简介',
  icon_key VARCHAR(32) NOT NULL COMMENT '内置图标Key',
  entry_type VARCHAR(16) NOT NULL COMMENT 'INTERNAL或EXTERNAL',
  route VARCHAR(255) NULL COMMENT '内部登记路由',
  external_url VARCHAR(2048) NULL COMMENT '批准的外部地址；空代表待配置',
  visible_roles JSON NOT NULL COMMENT '可见角色数组',
  sort_order INT NOT NULL DEFAULT 0 COMMENT '升序排序',
  enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
  row_version INT NOT NULL DEFAULT 0 COMMENT '并发版本',
  PRIMARY KEY (id),
  CONSTRAINT ck_hub_system_deleted CHECK (deleted IN (0,1)),
  UNIQUE KEY uk_system_code (code),
  KEY idx_system_order (enabled, deleted, sort_order, id),
  CHECK (enabled IN (0,1)),
  CHECK ((entry_type='INTERNAL' AND route IS NOT NULL AND external_url IS NULL) OR (entry_type='EXTERNAL' AND route IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='可扩展系统卡片';

CREATE TABLE puzzle (
  id BIGINT NOT NULL COMMENT '应用生成的正整数ID',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'UTC创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'UTC更新时间，应用显式维护',
  create_by BIGINT NULL COMMENT '创建者，系统任务可空',
  update_by BIGINT NULL COMMENT '最后更新者',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除0正常1删除',
  owner_id BIGINT NOT NULL COMMENT '所有者',
  status VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/PUBLISHED/ARCHIVED',
  latest_version_id BIGINT NULL COMMENT '最新草稿；仅创建事务中短暂允许空',
  published_version_id BIGINT NULL COMMENT '公开版本，归档保留，恢复清空',
  row_version INT NOT NULL DEFAULT 0 COMMENT '每次保存或状态动作递增',
  PRIMARY KEY (id),
  CONSTRAINT ck_puzzle_deleted CHECK (deleted IN (0,1)),
  KEY idx_puzzle_owner (owner_id, deleted, update_time, id),
  KEY idx_puzzle_status (status, deleted, update_time, id),
  FOREIGN KEY (owner_id) REFERENCES sys_user(id),
  CHECK (status IN ('DRAFT','PUBLISHED','ARCHIVED')),
  CHECK (status<>'PUBLISHED' OR published_version_id IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='题目生命周期与版本指针';

CREATE TABLE puzzle_version (
  id BIGINT NOT NULL COMMENT '应用生成的正整数ID',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'UTC创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'UTC更新时间，应用显式维护',
  create_by BIGINT NULL COMMENT '创建者，系统任务可空',
  update_by BIGINT NULL COMMENT '最后更新者',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除0正常1删除',
  puzzle_id BIGINT NOT NULL COMMENT '所属题目',
  version_no INT NOT NULL COMMENT '题内递增版本号',
  title VARCHAR(120) NOT NULL COMMENT '标题',
  description TEXT NOT NULL COMMENT '说明，API最多2000字符',
  tags JSON NOT NULL COMMENT '去重标签数组，最多10个',
  difficulty VARCHAR(16) NOT NULL COMMENT '人工难度',
  allowed_first_seats JSON NOT NULL COMMENT '允许的先手数组，只能含0(USER)/1(BOT)',
  ruleset_version VARCHAR(32) NOT NULL COMMENT 'CLASSIC_V1',
  schema_version INT NOT NULL DEFAULT 1 COMMENT '局面序列化版本',
  initial_state JSON NOT NULL COMMENT '完整双人GameState',
  state_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '规范化状态SHA256；命中后还需核对原文',
  PRIMARY KEY (id),
  CONSTRAINT ck_puzzle_version_deleted CHECK (deleted IN (0,1)),
  UNIQUE KEY uk_puzzle_version (puzzle_id, version_no),
  UNIQUE KEY uk_version_parent (puzzle_id, id),
  KEY idx_version_hash (state_hash),
  FOREIGN KEY (puzzle_id) REFERENCES puzzle(id),
  CHECK (difficulty IN ('EASY','MEDIUM','HARD')),
  CHECK (version_no>0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='不可变题目内容和局面';

CREATE TABLE game_session (
  id BIGINT NOT NULL COMMENT '应用生成的正整数ID',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'UTC创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'UTC更新时间，应用显式维护',
  create_by BIGINT NULL COMMENT '创建者，系统任务可空',
  update_by BIGINT NULL COMMENT '最后更新者',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除0正常1删除',
  owner_id BIGINT NOT NULL COMMENT '用户',
  puzzle_version_id BIGINT NOT NULL COMMENT '绑定版本',
  first_seat TINYINT NOT NULL COMMENT '首手座位0(USER)/1(BOT)',
  mode VARCHAR(16) NOT NULL COMMENT 'TRAINING/OPTIMAL',
  status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' COMMENT '对局状态',
  initial_state JSON NOT NULL COMMENT '创建快照',
  current_state JSON NOT NULL COMMENT '当前完整状态',
  state_version INT NOT NULL DEFAULT 0 COMMENT '行动/放弃时递增',
  winner_side VARCHAR(16) NULL COMMENT '终局阵营USER/BOT',
  robot_status VARCHAR(16) NOT NULL DEFAULT 'IDLE' COMMENT '机器人调度状态',
  hint_count INT NOT NULL DEFAULT 0 COMMENT '使用提示次数',
  proof_result_id BIGINT NULL COMMENT '当前最优模式引用的结果，后置外键',
  parent_game_id BIGINT NULL COMMENT '重开的来源',
  finished_time DATETIME(3) NULL COMMENT '终态时间',
  PRIMARY KEY (id),
  CONSTRAINT ck_game_session_deleted CHECK (deleted IN (0,1)),
  KEY idx_game_owner (owner_id, status, deleted, update_time, id),
  FOREIGN KEY (owner_id) REFERENCES sys_user(id),
  FOREIGN KEY (puzzle_version_id) REFERENCES puzzle_version(id),
  FOREIGN KEY (parent_game_id) REFERENCES game_session(id),
  CHECK (first_seat BETWEEN 0 AND 1),
  CHECK (mode IN ('TRAINING','OPTIMAL')),
  CHECK (status IN ('ACTIVE','FINISHED','ABANDONED')),
  CHECK ((status='FINISHED' AND winner_side IS NOT NULL AND winner_side IN ('USER','BOT')) OR (status<>'FINISHED' AND winner_side IS NULL)),
  CHECK (robot_status IN ('IDLE','QUEUED','THINKING','NEEDS_PROOF','FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='对局权威快照';

CREATE TABLE game_action (
  id BIGINT NOT NULL COMMENT '应用生成的正整数ID',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'UTC创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'UTC更新时间，应用显式维护',
  create_by BIGINT NULL COMMENT '创建者，系统任务可空',
  update_by BIGINT NULL COMMENT '最后更新者',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除0正常1删除',
  game_id BIGINT NOT NULL COMMENT '所属对局',
  sequence_no INT NOT NULL COMMENT '从1连续递增',
  actor_seat TINYINT NOT NULL COMMENT 'USER=0/BOT=1',
  actor_type VARCHAR(16) NOT NULL COMMENT 'HUMAN/BOT',
  move_json JSON NOT NULL COMMENT '规范化Move',
  before_version INT NOT NULL COMMENT '前版本',
  after_version INT NOT NULL COMMENT '后版本',
  after_state JSON NOT NULL COMMENT '行动后的完整快照',
  decision_quality VARCHAR(16) NOT NULL COMMENT 'OPTIMAL/PROVEN/HEURISTIC/HUMAN',
  request_key VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '人类幂等Key或机器人作业Key',
  PRIMARY KEY (id),
  CONSTRAINT ck_game_action_deleted CHECK (deleted IN (0,1)),
  UNIQUE KEY uk_action_sequence (game_id, sequence_no),
  UNIQUE KEY uk_action_request (game_id, request_key),
  FOREIGN KEY (game_id) REFERENCES game_session(id),
  CHECK (actor_seat BETWEEN 0 AND 1),
  CHECK (after_version=before_version+1),
  CHECK (actor_type IN ('HUMAN','BOT')),
  CHECK (decision_quality IN ('OPTIMAL','PROVEN','HEURISTIC','HUMAN'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='不可变出牌/不出事件';

CREATE TABLE game_bot_job (
  id BIGINT NOT NULL COMMENT '应用生成的正整数ID',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'UTC创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'UTC更新时间，应用显式维护',
  create_by BIGINT NULL COMMENT '创建者，系统任务可空',
  update_by BIGINT NULL COMMENT '最后更新者',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除0正常1删除',
  game_id BIGINT NOT NULL COMMENT '对局',
  state_version INT NOT NULL COMMENT '依据的版本',
  status VARCHAR(16) NOT NULL DEFAULT 'QUEUED' COMMENT 'QUEUED/RUNNING/DONE/CANCELLED/FAILED',
  lease_token VARCHAR(64) NULL COMMENT '每次领取生成的新隔离令牌',
  lease_until DATETIME(3) NULL COMMENT '租约失效时间',
  attempt_count INT NOT NULL DEFAULT 0 COMMENT '领取次数',
  available_time DATETIME(3) NOT NULL COMMENT '重试可领取时间',
  PRIMARY KEY (id),
  CONSTRAINT ck_game_bot_job_deleted CHECK (deleted IN (0,1)),
  UNIQUE KEY uk_bot_version (game_id, state_version),
  KEY idx_bot_claim (status, available_time, lease_until),
  FOREIGN KEY (game_id) REFERENCES game_session(id),
  CHECK (status IN ('QUEUED','RUNNING','DONE','CANCELLED','FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='机器人持久调度，可重启恢复';

CREATE TABLE solve_task (
  id BIGINT NOT NULL COMMENT '应用生成的正整数ID',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'UTC创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'UTC更新时间，应用显式维护',
  create_by BIGINT NULL COMMENT '创建者，系统任务可空',
  update_by BIGINT NULL COMMENT '最后更新者',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除0正常1删除',
  owner_id BIGINT NOT NULL COMMENT '提交者',
  purpose VARCHAR(16) NOT NULL COMMENT 'ANALYSIS/HINT',
  source_type VARCHAR(24) NOT NULL COMMENT 'PUZZLE_VERSION/GAME/CUSTOM',
  puzzle_version_id BIGINT NULL COMMENT '题目来源',
  game_id BIGINT NULL COMMENT '对局来源',
  game_state_version INT NULL COMMENT '对局来源版本',
  state_snapshot JSON NOT NULL COMMENT '不可变求解输入',
  state_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '规范化摘要',
  ruleset_version VARCHAR(32) NOT NULL COMMENT '规则版本',
  solver_version VARCHAR(64) NOT NULL COMMENT '运行算法版本，领取时固定',
  task_status VARCHAR(16) NOT NULL DEFAULT 'QUEUED' COMMENT '任务状态',
  time_limit_ms INT NOT NULL COMMENT '实际预算',
  node_limit BIGINT NOT NULL COMMENT '节点上限',
  memory_limit_mb INT NOT NULL COMMENT '搜索缓存预算',
  termination_reason VARCHAR(24) NULL COMMENT '结束原因',
  lease_token VARCHAR(64) NULL COMMENT '领取隔离令牌',
  lease_until DATETIME(3) NULL COMMENT '租约截止',
  attempt_count INT NOT NULL DEFAULT 0 COMMENT '领取次数',
  available_time DATETIME(3) NOT NULL COMMENT '排队/重试时间',
  start_time DATETIME(3) NULL COMMENT '首次开始时间',
  finish_time DATETIME(3) NULL COMMENT '结束时间',
  stats_json JSON NOT NULL COMMENT 'SolveStats进度快照',
  error_code VARCHAR(64) NULL COMMENT '脱敏错误码',
  PRIMARY KEY (id),
  CONSTRAINT ck_solve_task_deleted CHECK (deleted IN (0,1)),
  KEY idx_task_owner (owner_id, deleted, create_time, id),
  KEY idx_task_claim (task_status, available_time, lease_until),
  KEY idx_task_hash (state_hash, solver_version),
  FOREIGN KEY (owner_id) REFERENCES sys_user(id),
  FOREIGN KEY (puzzle_version_id) REFERENCES puzzle_version(id),
  FOREIGN KEY (game_id) REFERENCES game_session(id),
  CHECK (task_status IN ('QUEUED','RUNNING','COMPLETED','CANCELLED','FAILED')),
  CHECK (purpose IN ('ANALYSIS','HINT')),
  CHECK (time_limit_ms BETWEEN 100 AND 60000),
  CHECK (node_limit BETWEEN 1000 AND 5000000),
  CHECK (memory_limit_mb BETWEEN 16 AND 128),
  CHECK ((source_type='CUSTOM' AND puzzle_version_id IS NULL AND game_id IS NULL AND game_state_version IS NULL) OR (source_type='PUZZLE_VERSION' AND puzzle_version_id IS NOT NULL AND game_id IS NULL AND game_state_version IS NULL) OR (source_type='GAME' AND puzzle_version_id IS NULL AND game_id IS NOT NULL AND game_state_version IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='持久分析任务及计算快照';

CREATE TABLE solve_result (
  id BIGINT NOT NULL COMMENT '应用生成的正整数ID',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'UTC创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'UTC更新时间，应用显式维护',
  create_by BIGINT NULL COMMENT '创建者，系统任务可空',
  update_by BIGINT NULL COMMENT '最后更新者',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除0正常1删除',
  task_id BIGINT NOT NULL COMMENT '所属任务唯一',
  proof_status VARCHAR(16) NOT NULL COMMENT 'PROVEN/UNKNOWN',
  winner_side VARCHAR(16) NULL COMMENT '获胜阵营USER/BOT',
  proof_value TINYINT NULL COMMENT 'USER视角+1或-1',
  strategy_status VARCHAR(16) NOT NULL COMMENT 'NONE/PARTIAL/COMPLETE',
  root_node_id BIGINT NULL COMMENT '证明根节点，后置复合外键',
  winning_lines_json JSON NOT NULL COMMENT '最多5条已验证展示路线',
  stats_json JSON NOT NULL COMMENT '最终统计',
  verified_time DATETIME(3) NULL COMMENT '完整证明校验时间',
  PRIMARY KEY (id),
  CONSTRAINT ck_solve_result_deleted CHECK (deleted IN (0,1)),
  UNIQUE KEY uk_result_task (task_id),
  FOREIGN KEY (task_id) REFERENCES solve_task(id),
  CHECK ((proof_status='UNKNOWN' AND winner_side IS NULL AND proof_value IS NULL) OR (proof_status='PROVEN' AND winner_side IS NOT NULL AND proof_value IS NOT NULL AND ((winner_side='USER' AND proof_value=1) OR (winner_side='BOT' AND proof_value=-1)))),
  CHECK (strategy_status IN ('NONE','PARTIAL','COMPLETE')),
  CHECK (strategy_status<>'COMPLETE' OR (proof_status='PROVEN' AND root_node_id IS NOT NULL AND verified_time IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='每任务一个根结论';

CREATE TABLE strategy_node (
  id BIGINT NOT NULL COMMENT '应用生成的正整数ID',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'UTC创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'UTC更新时间，应用显式维护',
  create_by BIGINT NULL COMMENT '创建者，系统任务可空',
  update_by BIGINT NULL COMMENT '最后更新者',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除0正常1删除',
  result_id BIGINT NOT NULL COMMENT '所属结果',
  state_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '规范化摘要',
  state_json JSON NOT NULL COMMENT '局面',
  proof_status VARCHAR(16) NOT NULL COMMENT '节点证明状态',
  winner_side VARCHAR(16) NULL COMMENT '节点获胜方USER/BOT',
  coverage VARCHAR(16) NOT NULL COMMENT 'TERMINAL/ONE_WINNING/ALL_REPLIES/PARTIAL',
  terminal TINYINT NOT NULL DEFAULT 0 COMMENT '是否终局',
  PRIMARY KEY (id),
  CONSTRAINT ck_strategy_node_deleted CHECK (deleted IN (0,1)),
  UNIQUE KEY uk_node_hash (result_id, state_hash),
  UNIQUE KEY uk_node_result (result_id, id),
  FOREIGN KEY (result_id) REFERENCES solve_result(id),
  CHECK (terminal IN (0,1)),
  CHECK ((proof_status='UNKNOWN' AND winner_side IS NULL) OR (proof_status='PROVEN' AND winner_side IS NOT NULL AND winner_side IN ('USER','BOT'))),
  CHECK (coverage IN ('TERMINAL','ONE_WINNING','ALL_REPLIES','PARTIAL'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='结果内去重证明局面';

CREATE TABLE strategy_edge (
  id BIGINT NOT NULL COMMENT '应用生成的正整数ID',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'UTC创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'UTC更新时间，应用显式维护',
  create_by BIGINT NULL COMMENT '创建者，系统任务可空',
  update_by BIGINT NULL COMMENT '最后更新者',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除0正常1删除',
  result_id BIGINT NOT NULL COMMENT '所属结果',
  from_node_id BIGINT NOT NULL COMMENT '起点',
  to_node_id BIGINT NOT NULL COMMENT '终点',
  move_json JSON NOT NULL COMMENT '合法行动',
  move_key VARCHAR(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '规范化行动字符串',
  recommended TINYINT NOT NULL DEFAULT 0 COMMENT '是否建议',
  sort_order INT NOT NULL COMMENT '稳定分页序号',
  PRIMARY KEY (id),
  CONSTRAINT ck_strategy_edge_deleted CHECK (deleted IN (0,1)),
  UNIQUE KEY uk_edge_move (result_id, from_node_id, move_key),
  KEY idx_edge_children (result_id, from_node_id, sort_order, id),
  FOREIGN KEY (result_id, from_node_id) REFERENCES strategy_node(result_id, id),
  FOREIGN KEY (result_id, to_node_id) REFERENCES strategy_node(result_id, id),
  CHECK (recommended IN (0,1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='证明行动边及覆盖';

CREATE TABLE audit_log (
  id BIGINT NOT NULL COMMENT '应用生成的正整数ID',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'UTC创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'UTC更新时间，应用显式维护',
  create_by BIGINT NULL COMMENT '创建者，系统任务可空',
  update_by BIGINT NULL COMMENT '最后更新者',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除0正常1删除',
  actor_id BIGINT NULL COMMENT '操作者',
  action VARCHAR(64) NOT NULL COMMENT '业务动作码',
  resource_type VARCHAR(32) NOT NULL COMMENT '资源类型',
  resource_id BIGINT NULL COMMENT '资源ID',
  request_id VARCHAR(64) NOT NULL COMMENT '请求关联',
  outcome VARCHAR(16) NOT NULL COMMENT 'SUCCESS/FAILURE',
  details_json JSON NOT NULL COMMENT '脱敏差异或错误码',
  PRIMARY KEY (id),
  CONSTRAINT ck_audit_log_deleted CHECK (deleted IN (0,1)),
  KEY idx_audit_resource (resource_type, resource_id, create_time),
  KEY idx_audit_actor (actor_id, create_time),
  CHECK (outcome IN ('SUCCESS','FAILURE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='关键动作审计，不存秘密';

CREATE TABLE idempotency_record (
  id BIGINT NOT NULL COMMENT '应用生成的正整数ID',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'UTC创建时间',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'UTC更新时间，应用显式维护',
  create_by BIGINT NULL COMMENT '创建者，系统任务可空',
  update_by BIGINT NULL COMMENT '最后更新者',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除0正常1删除',
  owner_id BIGINT NOT NULL COMMENT '调用者',
  operation VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'API路径或内部操作码',
  request_key VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '幂等键',
  payload_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '规范化请求的服务端HMAC摘要，不保存密码',
  status VARCHAR(16) NOT NULL COMMENT 'PROCESSING/COMPLETED',
  response_json JSON NULL COMMENT '成功响应或资源引用，不含敏感字段',
  expires_time DATETIME(3) NOT NULL COMMENT '默认24小时；到期返回KEY_EXPIRED，不重用键',
  PRIMARY KEY (id),
  CONSTRAINT ck_idempotency_record_deleted CHECK (deleted IN (0,1)),
  UNIQUE KEY uk_idem_scope (owner_id, operation, request_key),
  KEY idx_idem_expiry (expires_time),
  FOREIGN KEY (owner_id) REFERENCES sys_user(id),
  CHECK (status IN ('PROCESSING','COMPLETED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='写请求幂等；凭证类不缓存完整请求';

-- 双向指针在两端建表后添加；复合外键保证指针属于同一题目/结果。
ALTER TABLE puzzle ADD CONSTRAINT fk_puzzle_latest FOREIGN KEY (id, latest_version_id) REFERENCES puzzle_version(puzzle_id, id), ADD CONSTRAINT fk_puzzle_published FOREIGN KEY (id, published_version_id) REFERENCES puzzle_version(puzzle_id, id);
ALTER TABLE solve_result ADD CONSTRAINT fk_result_root FOREIGN KEY (id, root_node_id) REFERENCES strategy_node(result_id, id);
ALTER TABLE game_session ADD CONSTRAINT fk_game_proof FOREIGN KEY (proof_result_id) REFERENCES solve_result(id);
